### ISSUE TITLE
Provide access to data in the primary ccsds header

### ISSUE THREAD

**Issue by ehsteve** [ddasilva/ccsdspy#15]
The class `ccsdspy.FixedLength` provides `load()` which returns a dictionary with the data from the packet fields but does not provide any info from the primary ccsds header. 

Values which would be very helpful would be
-  the `ap_id` 
-  an array of the packet counts. Packet counters which would helpful to ensure that no packets were missed.

My preference would be to provide all of the cssds header values.

**Comment by ddasilva** [comment]
Thanks for the suggestion @ehsteve !

This makes sense, especially for debugging. Notionally. in most cases where you would know enough about the packet to define it's fields for CCSDSPy you would also know the APID of the packet. But it would make sense to have this as a backup check to ensure that stream that of supposedly all the same APID is really so.

I think this could be implemented as a keyword argument `include_primary_header=True` in the `load()` method, which if set (default to False) will include primary header fields in the return dictionary (maybe with some prefix to the keys eg `Header:apid`. Or maybe return two dictionaries. What do you think?

**Comment by ehsteve** [comment]
I like that approach!
