### ISSUE TITLE
Raise a warning if sequence count is non-consecutive

### ISSUE THREAD

**Issue by ehsteve** [ddasilva/ccsdspy#21]
To let the user know if the packet sequence count in the primary header skips a number which would imply that a packet was lost. The sequence count is per APID therefore they would have to be checked individually.

**Comment by ddasilva** [comment]
Sounds reasonable. We might make this an option set to True by default, eg `warning_on_missing_packet=True`. We may also consider making our subclasses of warning, eg `CCSDSPyWarning -> ParsingWarning -> MissingPacketWarning` or something like that

**Comment by ddasilva** [comment]
Depends on #15

**Comment by ehsteve** [comment]
@ddasilva this can be closed.
