### ISSUE TITLE
Update the badge in README to point to github action results

### ISSUE THREAD

**Issue by ehsteve** [ddasilva/ccsdspy#27]
The badge currently points to travis. Github actions can generate badges as well. See the official [documentation](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge).

**Comment by ddasilva** [comment]
Are you sure? It seems to point to github actions to me.
https://raw.githubusercontent.com/ddasilva/ccsdspy/main/README.rst

**Comment by ehsteve** [comment]
You are right. This got fixed at some point.
