### ISSUE TITLE
Add coverage checking

### ISSUE THREAD

**Issue by ehsteve** [ddasilva/ccsdspy#32]
It's a good idea to monitor and track test coverage to make sure that coverage is not decreasing over time. There are some free tools like [codecov](https://about.codecov.io/) that integrate with github actions and provide a coverage badge as well as coverage feedback on each merge request. See this [README](https://github.com/HERMES-SOC/hermes_core) for an example of the badge and this [merge request](https://github.com/HERMES-SOC/hermes_core/pull/25) to see an example of codecov reports.

**Comment by ddasilva** [comment]
This has been completed, and the coverage badge has been added to the README and website. we're currently at 91% coverage.

**Comment by ddasilva** [comment]
I added some more tests, and we're up to 96%
