### ISSUE TITLE
Provide version number

### ISSUE THREAD

**Issue by ehsteve** [ddasilva/ccsdspy#33]
This is required for operational code to be able to pin the required version to a stable release.

**Comment by ehsteve** [comment]
Looks like there is an official version on pypi (see [ccsdspy](https://pypi.org/project/ccsdspy/) though the library itself does not seem to provide a version. Not sure if this is compatible with standard python package version pinning such as in requirements files.

**Comment by ddasilva** [comment]
The version pypi uses is in setup.py. Exposing in __version__ seems like a good idea

**Comment by ehsteve** [comment]
A nice tool to manage version numbers is https://pypi.org/project/setuptools-scm/. This links your git tags and git releases to your version number. For those that cloned the repo, it also adds a dev tag to the version number so that they know that they are using the "bleeding" edge.

**Comment by ddasilva** [comment]
Related to #42
