### ISSUE TITLE
Add documentation for variable length packets

### ISSUE THREAD

**Issue by ehsteve** [ddasilva/ccsdspy#39]
Looks like there isn't an example provided for variable length packets besides the API reference.

**Comment by ddasilva** [comment]
Agreed, this is a good idea. Do you think the front page is too long? We could add this as another section under the `FixedLength` example, or we could add a variable length page on the sidebar and add text "For variable length packets, see the [Variable Length](#) page."

**Comment by ehsteve** [comment]
I started writing up a description of what I thought should be done but then decided it would be easier to just show you! see #41!

I tried to make the docs a bit more standardized. Sorry, I removed your custom navigation which I found confusing.

I also fixed the sphinx documentation links so you can now link to the code as well as link out to the dependencies like numpy.

**Comment by ddasilva** [comment]
The associated PR was merged and the site has been rebuild. closing
