### ISSUE TITLE
Package metadata like author and version should be moved 

### ISSUE THREAD

**Issue by ehsteve** [ddasilva/ccsdspy#42]
The standard place for this information to live in [pyproject.toml](https://peps.python.org/pep-0621). All of the python tooling can then extract the information from there.

**Comment by ddasilva** [comment]
Sounds reasonable! I had set up the project well before that PEP existed... it's about time

**Comment by ehsteve** [comment]
Wow! This package is much older than I knew. I would suggest that we use [poetry](https://python-poetry.org) to manage this though it is a little new and would require new developers to install it but it makes so many things so much easier. Have a look. I can update the package if you want to go that direction.

**Comment by ddasilva** [comment]
Using poetry seems reasonable to me. As far as I can tell it still produces sdist tarballs compatible with PyPI and pip or people who don't have poetry. Would this lock us into any design decisions later?

**Comment by ehsteve** [comment]
I would not say so and changing things to not use poetry would not be too hard.

**Comment by ddasilva** [comment]
Go for it! Pull request welcome
