### ISSUE TITLE
Byte ordering specified in PacketField not taken into account for float datatypes

### ISSUE THREAD

**Issue by 5tefan** [ddasilva/ccsdspy#7]
I am finding crazy values for float values among sane int and uint values. Changing byte_order for float datatypes did not resolve.  Digging in, it turns out that the default float datatype created from https://github.com/ddasilva/ccsdspy/blob/f3d9d9f45c950df0b8d0aa610396b845c27d1832/ccsdspy/decode.py#L63 defaults to system byteordering, probably little endian these days and will not work to parse bigendian. 

I'll open a resolving PR in a second.

**Comment by ddasilva** [comment]
Yikes! I had assumed that IEEE had spec'd out the endianness of floating points but I guess I was wrong. Thanks for fixing this.
